### ISSUE TITLE
@prefix: true

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-rc#3]
The prefixes should be explicitly prefixes.

**Comment by iherman** [comment]
Just to make it clear: dp you mean doing things like

```
        "dc" :  {
             "@id" : "http://purl.org/dc/elements/1.1/",
             "@prefix": "true"
        }
```

for all these terms? I can understand that this is good for 'documentation' purposes, but all the terms in the current file has `gen-delim` characters that make them suitable for CURIE-s anyway. I.e., this would not change the default behaviour for data files. (It may for compaction, though, so that may make sense in this respect).

**Comment by gkellogg** [comment]
I agree. `@prefix` is intended as an override. With IRIs ending in a gendelim, it is both unnecessary and overly complicated.
